### ISSUE TITLE
yes? indicates default N but returns true for empty user response

### ISSUE THREAD

**Issue by ivan** [bitwalker/artificery#1]
```elixir
  @spec yes?(String.t) :: boolean
  def yes?(question) when is_binary(question) do
    prompt = Color.style("? ", [:green]) <> question <> " (y/N) "
    reply = IO.gets(prompt)
    is_binary(reply) and String.trim(reply) in ["", "y", "Y", "yes", "Yes", "YES"]
  end
```

`yes?` prints `y/N` which implies `N` will be the default if the user just presses Enter, but the function chooses `y` and returns true.

Spotted during code review, I was not doing something with it.

**Comment by bitwalker** [comment]
Ah, yeah we should change that to `Y/n`, good catch!
