### ISSUE TITLE
Missing @impl

### ISSUE THREAD

**Issue by lpil** [bitwalker/artificery#2]
Hello!

In https://github.com/bitwalker/artificery/commit/fb3cb9e65d50402c2e5311f8f3ec4d5fba49d76d an `@impl` attribute was removed, however when I compile this library I get this warning:

```
==> artificery
Compiling 10 files (.ex)
warning: module attribute @impl was not set for function get/3 callback (specified in Access). This either means you forgot to add the "@impl true" annotation before the definition or that you are accidentally overriding this callback
  lib/command.ex:74
```

Was it correct to remove it?

**Comment by bitwalker** [comment]
Strange, it was causing a compilation failure for me, which is why I removed it. Now I wonder if maybe something on my end was messed up. I'll take a look :)
